### Get all offers from logged-in user
GET http://localhost:7000/offers/my-offers


### Offer help to a request => /offers/:requestId
POST http://localhost:7000/offers/67acb570526ea42d85d8b3f8
Content-Type: application/json

{
  "helperId": "67adcd35c4c83be241d12bf1",
  "message": "I can collect your mail."
}


### Get all offers for a specific request => offers/:requestId
GET http://localhost:7000/offers/67acb570526ea42d85d8b3fa



### Update offer => /offers/:offerId
PATCH http://localhost:7000/offers/67adf8f49bfc3f7e4a10d821
Content-Type: application/json

{
  "message": "I can collect your mail for the next days."
}


### Cancel own offer => offers/cancel/:offerId
DELETE http://localhost:7000/offers/cancel/67adf8f49bfc3f7e4a10d821



### Request creator rejects an offer => offers/reject/:offerId
// ❗❗ Request owner must be logged in in order to reject an offer ❗❗
// Check request owner on the response of /offers/my-offers
DELETE http://localhost:7000/offers/reject/67adf9569bfc3f7e4a10d83b
